# Main targets
.PHONY: all clean

all: output/report.pdf

# Final report
output/report.pdf: output/report.md output/downloads_histogram.png output/revisions_time.png output/editor_time.png output/editor_time0.png output/editor_time1.png output/revision.png output/time_at_editor.png output/main_issues.png
	cd $(dir $@) && pandoc $(notdir $<) -o $(notdir $@)

# Data preparation - github data produces two files
data/git-events.dta data/issues.dta: code/github.do github-data/data/raw/gitlog.csv github-data/data/temp/issues.csv
	stata -b do $<

# Durations script produces collapsed data for other analyses
temp/collapsed_year.dta temp/collapsed_accepted_at.dta: code/durations.do data/git-events.dta
	stata -b do $<

temp/zenodo.dta: code/zenodo.do 
	stata -b do $<

temp/issues.dta temp/git-events-processed.dta: code/issues.do data/git-events.dta data/issues.dta
	stata -b do $<

# Figure generation with explicit rules
output/revisions_time.png: code/revisions_time.do temp/collapsed_year.dta
	stata -b do $<

# Editor time figures - all three are generated by one script
output/editor_time.png output/editor_time0.png output/editor_time1.png: code/editor_time.do temp/collapsed_year.dta
	stata -b do $<

# Duration figures - both are generated by one script
output/revision.png output/time_at_editor.png: code/durations.do data/git-events.dta
	stata -b do $<

output/downloads_histogram.png: code/zenodo.do github-data/data/raw/zenodo-data.csv temp/zenodo.dta
	stata -b do $<

output/main_issues.png: code/issues.do temp/git-events-processed.dta temp/issues.dta
	stata -b do $<

# Zenodo data pull (if needed)
zenodo/zenodo_data_2022.csv: zenodo/zenodo_pull.py
	cd zenodo && python3 zenodo_pull.py

# Clean temporary files
clean:
	rm -f *.log
	rm -f temp/*.dta
	rm -f output/*.png output/*.pdf
